# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-20 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender_id', models.IntegerField(null=True)),
                ('login_name', models.CharField(max_length=32)),
                ('login_passwd', models.CharField(max_length=256)),
                ('status', models.CharField(default=1, max_length=4)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('pause_date', models.DateTimeField(null=True)),
                ('close_date', models.DateTimeField(null=True)),
                ('real_name', models.CharField(max_length=32)),
                ('idcard_no', models.CharField(max_length=64)),
                ('birthdate', models.DateTimeField()),
                ('gender', models.CharField(max_length=8, null=True)),
                ('occupation', models.CharField(max_length=32, null=True)),
                ('telephone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64, null=True)),
                ('mailaddress', models.CharField(max_length=128, null=True)),
                ('zipcode', models.CharField(max_length=128, null=True)),
                ('qq', models.CharField(max_length=32, null=True)),
                ('last_login_time', models.DateTimeField(null=True)),
                ('last_login_ip', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'ACCOUNT',
            },
        ),
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard_no', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'recommender',
            },
        ),
    ]
