# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-19 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FeeApp', '0001_initial'),
        ('AccountApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix_host', models.CharField(max_length=32)),
                ('os_username', models.CharField(max_length=32)),
                ('login_passwd', models.CharField(max_length=512)),
                ('status', models.NullBooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('pause_date', models.DateTimeField(null=True)),
                ('close_date', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountApp.Account')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeeApp.Cost')),
            ],
            options={
                'db_table': 'SERVICE',
            },
        ),
    ]
