# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-19 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_code', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('enrolldate', models.DateField()),
            ],
            options={
                'db_table': 'ADMIN_INFO',
            },
        ),
    ]
